# common application settings
app:
  host: null # any host will be checked
  port: 3000 # port to listen to

# reverse proxy server to send requests in gateway mode
proxy:
  disabled: true  # disable reverse proxy, will return default text otherwise
  scheme: http	  # http/https schema for target proxy host
  host: localhost # target host
  port: 3001	  # target port

# Logging settings
log:
  disabled: false # disable logging
  
  # logging response
  response:
    disabled: false # disable response logging
    # if blank string then will use Stdout
    #output: ./response.log # output results to file
    output: "" # output to stdout
    truncate: false # truncate file for output on start
    
    # RegEx strings that specify conditions when response should be logged. If contain empty string then allow all. 
    # Filters use AND as glue between conditionals
    conditions:
      disabled: false # disable conditions check
      request: # request check for response return
        disabled: false
        uri: "\\.php(\\?|$)"
        method: ""
        header: ""
        body: ""
      header: ""
      body: ""
    
  # logging request
  request:
    disabled: false # disable request logging
    #output: ./request.log # output results to file
    output: "" # output to stdout
    truncate: false # truncate file for output on start
            
    conditions:
      disabled: true # disable conditions check
      uri: ""
      header: ""
      method: ""
      body: ""
  
  # if blank string then will use Stderr
  error:
    disabled: false # disable logging
    #output: ./error.log # output results to file
    output: "" # output to stderr
    truncate: false # truncate file for output on start
